export enum ActionType {
  //Habits
  ADD_NEW_HABIT = "ADD_NEW_HABIT",
  GET_HABITS = "GET_HABITS",
  DELETE_HABIT = "DELETE_HABIT",
  UPDATE_HABIT = "UPDATE_HABIT",
  COMPLETE_HABIT = "COMPLETE_HABIT",
  UNCOMPLETE_HABIT = "UNCOMPLETE_HABIT",

  //flags
  CLOSE_INTER_AD = "CLOSE_INTER_AD",
  SHOW_INTER_AD = "SHOW_INTER_AD",
  GET_PRODUCTS = "GET_PRODUCTS",
  REMOVE_ADS = "REMOVE_ADS",
  TOGGLE_PAUSE_ADS = "TOGGLE_PAUSE_ADS",
  UPGRADE_PREMIUM = "UPGRADE_PREMIUM",

  //stats
  UPDATE_STATS = "UPDATE_STATS",
  GET_STATS = "GET_STATS",
  UPDATE_TODAY = "UPDATE_TODAY",

   //auth
   USER_LOADING = "USER_LOADING",
   USER_LOADED = "USER_LOADED",
   LOGIN_FAILED = "LOGIN_FAILED",
   LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
   LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL",
   AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
   AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
   AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS",
   AUTO_LOGIN = "AUTO_LOGIN",
   USERNAME_SUCCESS = "USERNAME_SUCCESS",
   PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",

   //Challenges
   GET_CHALLENGE = "GET_SETTINGS_FOR_CHALLENGE",
   UPDATE_CHALLENGE = "UPDATE_SETTINGS_FOR_CHALLENGE",
   UPDATE_CHALLENGE_STAT = "UPDATE_CHALLENGE_STAT",
}
